-- ============================================================
--  FINAL DATABASE SEED SCRIPT (final_script.sql)
--  Inserts all Employee Master Records and assigns initial HODs & Admin
-- ============================================================
USE [Rewards];
GO

PRINT 'Starting employee master seed...';

-- 1. Clear existing Employee tables with proper FK integrity
ALTER TABLE dbo.EmpRoles DROP CONSTRAINT IF EXISTS FK_EmpRoles_Employees;
ALTER TABLE dbo.EmpPasswords DROP CONSTRAINT IF EXISTS FK_EmpPasswords_Employees;

DELETE FROM dbo.EmpPasswords;
DELETE FROM dbo.EmpRoles;
DELETE FROM dbo.Employees;

-- Re-apply CASCADE foreign keys
ALTER TABLE dbo.EmpRoles ADD CONSTRAINT FK_EmpRoles_Employees
    FOREIGN KEY (Emp_No) REFERENCES dbo.Employees(Emp_No)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE dbo.EmpPasswords ADD CONSTRAINT FK_EmpPasswords_Employees
    FOREIGN KEY (Emp_No) REFERENCES dbo.Employees(Emp_No)
    ON DELETE CASCADE ON UPDATE CASCADE;
GO

-- 2. Insert into dbo.Employees
INSERT INTO dbo.Employees (Emp_No, DisplayName, Work_Email, Department, Location, Designation)
VALUES
    ('1332', 'Shekhar Kanifnath Khedekar', 'shekhar.khedekar@mahle.com', 'Production', 'PUNE', 'Asst. Manager'),
    ('1335', 'Sachin Dhamale C', 'sachdhamale@mahle.com', 'Purchase', 'PUNE', 'Sr. Engineer'),
    ('1336', 'Chopade Bajirao Nana', 'bajirao.chaupade@mahle.com', 'Production', 'PUNE', 'Engineer'),
    ('1337', 'Sanjay Nivruttirao Patode', 'sanjay.a.patode@mahle.com', 'Maintenance', 'PUNE', 'Sr. Engineer'),
    ('1351', 'Sandeep Baburao Malvi', 'sandeep.malvi@mahle.com', 'Process Engineering', 'PUNE', 'Manager'),
    ('1656', 'Polayi Mithun K', 'mithun.polayi@mahle.com', 'Engineering (R&D)', 'Head Office', 'Asst. Manager'),
    ('1693', 'Writusree Das', 'writushree.a.das@mahle.com', 'Supply Chain', 'PUNE', 'Sr. Engineer'),
    ('1729', 'Vinesh Kumar Jha', 'vinesh.jha@mahle.com', 'Production', 'PUNE', 'Engineer'),
    ('1754', 'Samanta Arindam', 'samanta.arindam@mahle.com', 'Central Quality', 'PUNE', 'Sr. Engineer'),
    ('1806', 'Jitendra Kumar', NULL, 'Maintenance', 'CHENNAI', 'Engineer'),
    ('1825', 'Jogdand Shuddhodhan Yashwant', 'shuddhodhan.jogdand@mahle.com', 'Production', 'PUNE', 'Engineer'),
    ('1828', 'Rajesh Chandrakant Mahangare', 'rajesh.mahangare@mahle.com', 'Maintenance', 'PUNE', 'Engineer'),
    ('1914', 'Prakash Kumar', 'prakash.a.kumar@mahle.com', 'Engineering (R&D)', 'PUNE', 'Engineer'),
    ('1935', 'Shivshankar Roy Roy', 'shivshankar.roy@mahle.com', 'SCM', 'PUNE', 'Sr. Engineer'),
    ('2028', 'Santosh Hanumant Mane', 'santosh.mane@mahle.com', 'Maintenance', 'PUNE', 'Sr. Engineer'),
    ('2162', 'Inteqhab Khan', 'inteqhab.khan@mahle.com', 'EHS', 'Parwanoo-1', 'Sr. Engineer'),
    ('2234', 'Shubham Singh', 'shubham.singh@mahle.com', 'Supply Chain', 'PUNE', 'Sr. Engineer'),
    ('6505', 'Shailesh R Nakhate', 'shailesh.nakhate@mahle.com', 'Central Purchase', 'PUNE', 'Manager'),
    ('6579', 'Kumbhar Rahul Yashwant', 'rahul.kumbhar@mahle.com', 'OE Marketing', 'PUNE', 'Sr. Manager'),
    ('6637', 'Jayprakash Manore', 'jayprakash.a.manore@mahle.com', 'Production', 'PUNE', 'GM'),
    ('6642', 'Ravikumar Sharanappa Dinni', 'Ravikumar.Dinni@mahle.com', 'Engineering (R&D)', 'PUNE', 'DGM'),
    ('6670', 'Prashant Prakash Tongire', 'prashant.tongire@mahle.com', 'Quality', 'PUNE', 'Manager'),
    ('6671', 'Prashant Chauhan', 'prashant.chauhan@mahle.com', 'SCM', 'Head Office', 'AGM'),
    ('6673', 'Maheswar Pati', 'maheswar.pati@mahle.com', 'Finance', 'PUNE', 'Manager'),
    ('6676', 'Saidutta Dipankar Biswal', 'dipankar.biswal@mahle.com', 'Supply Chain', 'PUNE', 'Asst. Manager'),
    ('6681', 'Rahul Kumar', 'rahul.c.kumar@mahle.com', 'PPC', 'PUNE', 'Sr. Engineer'),
    ('6682', 'Priya ranjan Sahoo', 'priyaranjan.sahoo@mahle.com', 'Maintenance', 'PUNE', 'Manager'),
    ('6685', 'Ganesh Parmeshwar surve', 'ganesh.surve@mahle.com', 'Maintenance', 'PUNE', 'Sr. Engineer'),
    ('6687', 'Sandeep Uttam Shinde', 'sandip.shinde@mahle.com', 'HR', 'PUNE', 'Sr. Executive'),
    ('6688', 'Shubham Kachrudas Sonawane', 'Shubham.Sonawane@mahle.com', 'Quality', 'PUNE', 'Sr. Engineer'),
    ('6689', 'Amol Jijabhau Said', 'amol.said@mahle.com', 'Purchase', 'PUNE', 'Sr. Engineer'),
    ('6690', 'Praveen Basavaraj Balekundri', 'praveen.balekundri@mahle.com', 'Engineering (R&D)', 'PUNE', 'Asst. Manager'),
    ('6691', 'Pradeep Shabadi', 'Pradeep.a.Shabadi@mahle.com', 'Engineering (R&D)', 'PUNE', 'Sr. Engineer'),
    ('6692', 'Jivan Ramesh Chaudhari', 'jivan.chaudhari@mahle.com', 'PROJECT MANAGEMENT', 'PUNE', 'Asst. Manager'),
    ('6694', 'Prashant Bhaskar Bhusari', 'Prashant.b.Bhusari@mahle.com', 'Engineering (R&D)', 'PUNE', 'Sr. Engineer'),
    ('6696', 'Jugnu Kumar Singh', 'JugnuKumar.Singh@mahle.com', 'Production', 'PUNE', 'Sr. Engineer'),
    ('6699', 'Vijay Garimella', 'vijay.garimella@mahle.com', 'Production', 'PUNE', 'Assistant Manager'),
    ('6701', 'Shrinivas Rajendra Shinde', 'shrinivas.shinde@mahle.com', 'Process Engineering', 'PUNE', 'Sr. Engineer'),
    ('6703', 'Ravichandra Appasaheb Mali', 'ravichandra.mali@mahle.com', 'Quality', 'PUNE', 'Senior Engineer'),
    ('6706', 'Abhijit Jaykrishna Deshpande', 'abhijit.deshpande@mahle.com', 'PROJECT MANAGEMENT', 'PUNE', 'DGM'),
    ('6707', 'Tushar Santosh Pawar', 'tushar.pawar@mahle.com', 'HR', 'PUNE', 'Sr. Manager'),
    ('6708', 'Shekhar Shashikant Sankpal', 'shekhar.sankpal@mahle.com', 'Quality', 'PUNE', 'Sr. Engineer'),
    ('6709', 'Dinesh Ramdas Satav', 'dinesh.satav@mahle.com', 'Quality', 'PUNE', 'Assistant Manager'),
    ('6711', 'Akshay Bhagwat Gayakwad', 'akshay.gayakwad@mahle.com', 'Central Quality', 'PUNE', 'Sr. Engineer'),
    ('6712', 'Aarti Ganpatrao Shinde', 'aarti.shinde@mahle.com', 'SCM', 'PUNE', 'Sr. Manager'),
    ('6713', 'Mihir Vivek Ratnakar', 'mihir.ratnakar@mahle.com', 'EHS', 'PUNE', 'Sr. Engineer'),
    ('1002', 'Palani Ashokan', 'p.ashokan@mahle.com', 'Process Engineering', 'CHENNAI', 'Sr. Manager'),
    ('1009', 'N Prem Kumar', 'n.premkumar@mahle.com', 'Tooling', 'CHENNAI', 'Sr. Manager'),
    ('1027', 'B Vasantha Kumar', 'vasanthakumar.baskaran@mahle.com', 'Central Process', 'CHENNAI', 'AGM'),
    ('1030', 'K P Arun', 'arun.narayanan@mahle.com', 'Central Process', 'Chennai-HO', 'Manager'),
    ('1031', 'R Shankar', 'shankar.rajendran@mahle.com', 'PROJECT MANAGEMENT', 'Chennai-HO', 'Sr. Manager'),
    ('1033', 'Sunil KUMAR', 'Sunilkumar.veersingh@mahle.com', 'Production', 'Khandsa', 'Asst. Manager'),
    ('1048', 'Raja R', 'raja.rajaram@mahle.com', 'Production', 'CHENNAI', 'Manager'),
    ('1052', 'Sanjeevi Kumar', 'sanjeevi.kumar@mahle.com', 'SCM', 'CHENNAI', 'Sr. Manager'),
    ('1077', 'Vijayaraghavan M', 'vijayaraghavan.muralidharan@mahle.com', 'Supply Chain', 'CHENNAI', 'Asst. Manager'),
    ('1078', 'K Sheik Jamaludeen', 'sheik.jamaludeen@mahle.com', 'Maintenance', 'CHENNAI', 'Assistant Manager'),
    ('1084', 'Ramkumar P', 'ramkumar.palanivel@mahle.com', 'Tooling', 'CHENNAI', 'Asst. Manager'),
    ('1088', 'Sowrimuthu A', 'chennai.maintenance@mahle.com', 'Maintenance', 'CHENNAI', 'Engineer'),
    ('1089', 'T Madhavan', 'madhavan.thangaraj@mahle.com', 'Purchase', 'CHENNAI', 'Asst. Manager'),
    ('1092', 'Sridhar K', 'sridhar.kannan@mahle.com', 'Production', 'CHENNAI', 'Sr. Manager'),
    ('1098', 'Kumaravel Ranganathan', 'kumaravel.ranganathan@mahle.com', 'Production', 'CHENNAI', 'Asst. Manager'),
    ('1099', 'V S Mohan Kumar', 'mohan.a.kumar@mahle.com', 'Maintenance', 'CHENNAI', 'Asst. Manager'),
    ('1105', 'Kalyanasundaram T', 'kalyanasundaram.t@mahle.com', 'Process Engineering', 'CHENNAI', 'Senior Engineer'),
    ('1107', 'Sai Ganesh H', 'saiganesh.h@mahle.com', 'Process Engineering', 'CHENNAI', 'Senior Engineer'),
    ('1108', 'Shyam Babu S', 'shyambabu.s@mahle.com', 'Quality', 'CHENNAI', 'Asst. Manager'),
    ('1109', 'Mareeswaran T', 'mareeswaran.t@mahle.com', 'HR', 'CHENNAI', 'Manager'),
    ('1110', 'Arun kumar R', 'arunkumar.r@mahle.com', 'Safety', 'CHENNAI', 'Sr. Engineer'),
    ('1112', 'Keerthivel', NULL, 'Tooling', 'CHENNAI', 'Engineer'),
    ('1113', 'Godha Yeshwanth Goud', 'yeshwanth.a.goud@mahle.com', 'Process Engineering', 'CHENNAI', 'Senior Engineer'),
    ('1114', 'Nancy Y', 'nancy.y@mahle.com', 'HR', 'CHENNAI', 'Assistant Manager'),
    ('1116', 'Vinayagam V', NULL, 'Maintenance', 'CHENNAI', 'Engineer'),
    ('1117', 'Srinivasan Lakshmanaperumal', NULL, 'Process Engineering', 'CHENNAI', 'Sr. Engineer'),
    ('1118', 'Rahuman N', NULL, 'Maintenance', 'CHENNAI', 'Engineer'),
    ('1119', 'Mikhail Prabhudas N', 'mikhailprabhudas.n@mahle.com', 'Quality', 'CHENNAI', 'Assistant Manager'),
    ('1120', 'Jeyavelu N', 'jeyavelu.n@mahle.com', 'Maintenance', 'CHENNAI', 'Assistant Manager'),
    ('1121', 'Sathish Kumar', 'sathishkumar.b@mahle.com', 'Quality', 'CHENNAI', 'Assistant Manager'),
    ('1122', 'Vivin TS', 'vivin.ts@mahle.com', 'Process Engineering', 'CHENNAI', 'Assistant Manager'),
    ('1123', 'Murugananthan A', NULL, 'Maintenance', 'CHENNAI', 'Senior Engineer'),
    ('6007', 'R Kumaresan', 'kumaresan.ramachandran@mahle.com', 'Quality', 'CHENNAI', 'Manager'),
    ('6009', 'Kulandai Veeramakali R', 'veera.rajendran@mahle.com', 'Supply Chain', 'CHENNAI', 'Sr. Engineer'),
    ('6074', 'G Anitha', 'anitha.ganesan@mahle.com', 'Supply Chain', 'CHENNAI', 'Engineer'),
    ('6096', 'Praveen Kumar', 'Praveenkumar.Selvaraj@mahle.com', 'Tooling', 'CHENNAI', 'Engineer'),
    ('6126', 'Korapati Yesanna', 'korapati.yesanna@mahle.com', 'Quality', 'CHENNAI', 'Engineer'),
    ('6139', 'Subramani', 'subramani.shanmugavel@mahle.com', 'Production', 'CHENNAI', 'Sr. Engineer'),
    ('6165', 'M.Rathinavel', NULL, 'Production', 'CHENNAI', 'Engineer'),
    ('6187', 'Sasikumar Marimuthu', 'Sasikumar.Marimuthu@mahle.com', 'Quality', 'CHENNAI', 'Engineer'),
    ('6215', 'Dibyendu chakraborty', 'Dibyendu.Chakraborty@mahle.com', 'Engineering (R&D)', 'PUNE', 'Engineer'),
    ('8021', 'Asif Aziz TP', 'asif.aziz@mahle.com', 'Central Quality', 'Chennai-HO', 'Engineer'),
    ('8409', 'Sivaperumal', NULL, 'Production', 'CHENNAI', 'Engineer'),
    ('8411', 'Gokulakrishnan Sankar', NULL, 'Production', 'CHENNAI', 'Asst. Engineer'),
    ('8412', 'R Vignesh', NULL, 'Production', 'CHENNAI', 'Asst. Engineer'),
    ('8413', 'Shubhadip Jana', NULL, 'Production', 'CHENNAI', 'Asst. Engineer'),
    ('E20067', 'Laxmi Prakash Pradhan', 'laxmi.pradhan@mahle.com', 'Production', 'Parwanoo-1', 'DGM'),
    ('E20070', 'Deepak Jangra', 'deepak.jangra@mahle.com', 'Central Quality', 'Head Office', 'AGM'),
    ('E20089', 'Kamal Kumar Panda', 'kamal.panda@mahle.com', 'Central Process', 'CHENNAI', 'DGM'),
    ('E20196', 'Raju Kumar Yadav', 'raju.yadav@mahle.com', 'Quality', 'Khandsa', 'Senior Engineer'),
    ('E40002', 'Anil Banta', 'anil.banta@mahle.com', 'After Market', 'Parwanoo-1', 'DGM'),
    ('E40007', 'Anuj Chauhan', 'anuj.chauhan@mahle.com', 'Engineering (R&D)', 'Parwanoo-1', 'Asst. Manager'),
    ('E40022', 'Banita Chaudhary', 'banita.chaudhary@mahle.com', 'Production', 'Parwanoo-1', 'Engineer'),
    ('E40032', 'Deepinder Singh', 'Deepinder.singh@mahle.com', 'Engineering (R&D)', 'Head Office', 'Engineer'),
    ('E40041', 'Ishita Bodh', 'ishita.bodh@mahle.com', 'Central Process', 'Head Office', 'Sr. Engineer'),
    ('E40053', 'Mohit Singla', 'mohit.singla@mahle.com', 'Central Purchase', 'Head Office', 'AGM'),
    ('E40055', 'Mohan Sharma', 'mohan.sharma@mahle.com', 'Process', 'Parwanoo-1', 'Asst. Manager'),
    ('E40065', 'Nishant Prasher', 'nishant.prasher@mahle.com', 'SCM', 'Parwanoo-1', 'Engineer'),
    ('E40069', 'Pradeep Thakur', 'pradeep.thakur@mahle.com', 'Quality', 'Parwanoo-1', 'Asst. Manager'),
    ('E40073', 'Pankush Kumar', 'pankush.kumar@mahle.com', 'Production', 'Parwanoo-1', 'Manager'),
    ('E40074', 'Ravinder Singh Bajwa', 'ravinder.bajwa@mahle.com', 'Finance', 'Head Office', 'Sr. Manager'),
    ('E40075', 'Reena Sharma', 'reena.sharma@mahle.com', 'Quality', 'Parwanoo-1', 'Manager'),
    ('E40082', 'Robin Pant', 'robpant@mahle.com', 'SCM', 'Parwanoo-1', 'Manager'),
    ('E40090', 'Shahnawaz Hussain', 'molvi.shahnawaj@mahle.com', 'After Market', 'Parwanoo-1', 'Manager'),
    ('E40093', 'Sanju Kumar', 'sanju.kumar@mahle.com', 'Process Engineering', 'Khandsa', 'Asst. Manager'),
    ('E40100', 'Sorabh Kalia', 'sorabh.kalia@mahle.com', 'Supply Chain', 'Parwanoo-1', 'Asst. Manager'),
    ('E40101', 'Sanjesh Chauhan', 'sanjesh.chauhan@mahle.com', 'Process Engineering', 'Parwanoo-1', 'Manager'),
    ('E40103', 'Tinku Jangra', 'Tinku.jangra@mahle.com', 'Supply Chain', 'Parwanoo-1', 'Asst. Manager'),
    ('E40209', 'Asha Kumari', 'asha.sharma@mahle.com', 'Supply Chain', 'Khandsa', 'Sr. Engineer'),
    ('E40292', 'Deepak Sharma', 'deepak.b.sharma@mahle.com', 'Quality', 'Parwanoo-1', 'Sr. Engineer'),
    ('E40297', 'Pawan Kumar', 'Pawan.c.Kumar@mahle.com', 'Central Quality', 'Parwanoo-1', 'Engineer'),
    ('E40370', 'Manisha Kumari', 'manisha.kumari@mahle.com', 'Quality', 'Parwanoo-1', 'Engineer'),
    ('E50002', 'Ashok Kumar Tanwar', 'ashok.tanwar@mahle.com', 'Finance', 'Parwanoo-1', 'Sr. Manager'),
    ('E50003', 'Ankush Kumar', 'ankush.chauhan@mahle.com', 'Purchase', 'Parwanoo-1', 'Asst. Manager'),
    ('E50013', 'Deepak Goyal', 'deepak.goyal@mahle.com', 'Central Purchase', 'Head Office', 'AGM'),
    ('E50037', 'Naresh Kumar', 'naresh.kumar@mahle.com', 'Maintenance', 'Parwanoo-1', 'Manager'),
    ('E50039', 'Puneet Kumar', 'puneet.a.kumar@mahle.com', 'Production', 'Khandsa', 'Sr. Engineer'),
    ('E50045', 'Satish Kumar Bhardwaj', 'satish.bhardwaj@mahle.com', 'Production', 'Parwanoo-1', 'Sr. Engineer'),
    ('E50076', 'Arun Chauhan', 'arun.chauhan@mahle.com', 'Production', 'Parwanoo-1', 'Sr. Engineer'),
    ('E50108', 'Jagbeer Singh', NULL, 'Production', 'Parwanoo-1', 'Engineer'),
    ('E50135', 'Puneet Bhardwaj', 'Puneet.Bhardwaj@mahle.com', 'Production', 'Parwanoo-1', 'Engineer'),
    ('E50162', 'Shashi Kumar', NULL, 'Production', 'Parwanoo-1', 'Engineer'),
    ('E50203', 'Yogesh Kumar', 'yogesh.kumar@mahle.com', 'Maintenance', 'Parwanoo-1', 'Sr. Engineer'),
    ('E50278', 'Anil Sharma', 'puneet.a.kumar@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('E50322', 'Sudhir Rai', NULL, 'Production', 'Khandsa', 'Engineer'),
    ('E50332', 'Deepak Sharma', 'deepak.c.sharma@mahle.com', 'Quality', 'Parwanoo-1', 'Engineer'),
    ('E50396', 'Mandeep Agan', 'mandeep.a.agan@mahle.com', 'Quality', 'Khandsa', 'Engineer'),
    ('E50432', 'Ankur', 'ankur.b.kumar@mahle.com', 'HR', 'Parwanoo-1', 'Asst. Manager'),
    ('E50433', 'Ramneek Sharma', 'ramneek.a.sharma@mahle.com', 'Quality', 'Parwanoo-1', 'Asst. Manager'),
    ('E50438', 'Parul Walia', 'parul.walia@mahle.com', 'HR', 'Parwanoo-1', 'Manager'),
    ('K0060', 'Manoj Yadav', 'manoj.yadav@mahle.com', 'Supply Chain', 'Khandsa', 'Asst. Manager'),
    ('K0075', 'Preeti Bhatia', 'preeti.bhatia@mahle.com', 'Central Quality', 'Head Office', 'Sr. Engineer'),
    ('K0099', 'Poonam Saini', 'poonam.saini@mahle.com', 'Central Quality', 'Head Office', 'Asst. Manager'),
    ('K01003', 'Ankit', 'ankit.yadav@mahle.com', 'Production', 'Khandsa', 'Manager'),
    ('K01013', 'NARESH KUMAR', 'hrd.khd@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K01028', 'SANGRAM KESHARI SAHOO', 'Sangramkeshari.Sahoo@mahle.com', 'Quality', 'CHENNAI', 'Engineer'),
    ('K01030', 'Masibur Rahaman', 'Masibur.Rahaman@mahle.com', 'Maintenance', 'Khandsa', 'Assistant Manager'),
    ('K01069', 'SAHIL', NULL, 'Production', 'Parwanoo-1', 'Engineer'),
    ('K01104', 'Suneel Kumar', 'suneel.kumar@mahle.com', 'Supply Chain', 'Khandsa', 'Sr. Engineer'),
    ('K01140', 'Rajat Kumar Chakrabarty', 'rajat.chakrabarty@mahle.com', 'After Market', 'Head Office', 'Sr. Engineer'),
    ('K01144', 'Anil Tiwari', 'anil.tiwari@mahle.com', 'Central Quality', 'Head Office', 'GM'),
    ('K01146', 'Ishan Arora', 'ishan.a.arora@mahle.com', 'Quality', 'Khandsa', 'Manager'),
    ('K01149', 'Varun Rana', 'varun.rana@mahle.com', 'Quality', 'Khandsa', 'Asst. Manager'),
    ('K01151', 'Abhishek Tripathi', 'abhishek.tripathi@mahle.com', 'Quality', 'Khandsa', 'Manager'),
    ('K01152', 'Shammy Sharma', 'shammy.sharma@mahle.com', 'Central Quality', 'PUNE', 'Asst. Manager'),
    ('K01153', 'Tarun Kumar', 'tarun.b.kumar@mahle.com', 'Process Engineering', 'Khandsa', 'Asst. Manager'),
    ('K01154', 'Rohan Mohata', 'rohan.mohata@mahle.com', 'Process Engineering', 'Khandsa', 'Sr. Engineer'),
    ('K01162', 'Avaya Kumar Moharana', 'avayakumar.moharana@mahle.com', 'Process Engineering', 'Khandsa', 'Manager'),
    ('K01163', 'Divya Akhouri', 'divya.akhouri@mahle.com', 'HR', 'Khandsa', 'Sr. Manager'),
    ('K01164', 'Mantasha Zafar', 'mantasha.zafar@mahle.com', 'HR', 'Khandsa', 'Asst. Manager'),
    ('K01166', 'Vipin Singh Tomar', NULL, 'Maintenance', 'Khandsa', 'Engineer'),
    ('K01167', 'Ritesh Tiwari', 'ritesh.tiwari@mahle.com', 'Quality', 'Khandsa', 'Sr. Engineer'),
    ('K01168', 'Rohit Yadav', 'rohit.a.yadav@mahle.com', 'HR', 'Khandsa', 'Assistant Manager'),
    ('K01169', 'Vishal Singh', 'vishal.a.singh@mahle.com', 'Process Engineering', 'Khandsa', 'Assistant Manager'),
    ('K01170', 'Rohit Bhatt', 'rohit.bhatt@mahle.com', 'Quality', 'Khandsa', 'Manager'),
    ('K01171', 'Ajay Yadav', 'ajay.a.yadav@mahle.com', 'SCM', 'Khandsa', 'Sr. Executive'),
    ('K01172', 'Nitish Kumar', NULL, 'Process Engineering', 'Khandsa', 'Assistant Manager'),
    ('K0350', 'Praveen Kumar', 'praveen.kumar@mahle.com', 'Purchase', 'Khandsa', 'Asst. Manager'),
    ('K0378', 'Hari Gopal Singh', 'harigopal.singh@mahle.com', 'Production', 'Khandsa', 'Asst. Manager'),
    ('K0407', 'Rajeshwar Kumar Nishad', 'rajeshwar.nishad@mahle.com', 'Supply Chain', 'Khandsa', 'Asst. Manager'),
    ('K0433', 'SUNIL KUMAR', 'sunilkumar.dhetarwal@mahle.com', 'Dispatch', 'Khandsa', 'Manager'),
    ('K0462', 'Akshaya Kumar Sutar', 'akshaya.kumar@mahle.com', 'Supply Chain', 'Khandsa', 'Asst. Manager'),
    ('K0569', 'Dinesh Kumar Kavrhe', 'dinesh.kavrhe@mahle.com', 'Supply Chain', 'PUNE', 'Asst. Manager'),
    ('K0577', 'Jaibir Singh', 'jaibir.singh1@mahle.com', 'Maintenance', 'Khandsa', 'Asst. Manager'),
    ('K0592', 'Manoj Naithani', 'manoj.naithani@mahle.com', 'Finance', 'Head Office', 'DGM'),
    ('K0610', 'Jitendra Kumar Sahoo', 'jitendra.kumar.sahoo@mahle.com', 'Quality', 'Khandsa', 'Sr. Engineer'),
    ('K0676', 'RAKESH KUMAR', 'rakesh.f.kumar@mahle.com', 'Production', 'Khandsa', 'Assistant Manager'),
    ('K0692', 'Pawan Kumar', 'pawan.b.kumar@mahle.com', 'Central Quality', 'Head Office', 'Sr. Engineer'),
    ('K0693', 'Dinesh Kumar', 'dinesh.a.kumar@mahle.com', 'Quality', 'Khandsa', 'Sr. Engineer'),
    ('K0713', 'RISHI KUMAR', 'rishi.kumar@mahle.com', 'Supply Chain', 'Khandsa', 'Engineer'),
    ('K0723', 'SANDEEP KUMAR', 'hrd.khd@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K0729', 'PAWAN KUMAR', 'hrd.khd@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K0742', 'Surekha', 'surekha.rohila@mahle.com', 'Maintenance', 'Khandsa', 'Sr. Engineer'),
    ('K0750', 'SAPNA DEVI', 'sapna.saini@mahle.com', 'HR', 'Khandsa', 'Senior Executive'),
    ('K0771', 'HARDEEP SINGH', 'hardeep.a.singh@mahle.com', 'Central Purchase', 'Head Office', 'Sr. Engineer'),
    ('K0773', 'Bijender Singh', 'bijender.c.@mahle.com', 'Production', 'Khandsa', 'Asst. Manager'),
    ('K0777', 'DIWAN JAMSHED KHAN', 'jamshed.khan@mahle.com', 'EHS', 'Khandsa', 'Sr. Engineer'),
    ('K0800', 'Ashish Kumar Samantaray', 'Ashish.Samantaray@mahle.com', 'Central Process', 'Head Office', 'Manager'),
    ('K0822', 'JASBIR SINGH', 'hrd.khd@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K0826', 'GURMEET SINGH', 'gurmeet.a.singh@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K0827', 'Prashant Kumar Tiwary', 'prashant.tiwari@mahle.com', 'Maintenance', 'Khandsa', 'Sr. Engineer'),
    ('K0845', 'Sarika', 'sarika.choudhary@mahle.com', 'Central Quality', 'Head Office', 'Sr. Engineer'),
    ('K0854', 'Manu Kant', 'manu.kant@mahle.com', 'Maintenance', 'Khandsa', 'Manager'),
    ('K0856', 'Bhal Singh', 'bhal.singh@mahle.com', 'Central Quality', 'Head Office', 'Manager'),
    ('K0867', 'AVINASH SINGH MEHRA', 'hrd.khd@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K0871', 'ANSHUL CHAUHAN', 'anshul.chauhan@mahle.com', 'Supply Chain', 'Head Office', 'Senior Executive'),
    ('K0915', 'REHAN ALI', 'Rehan.Ali@mahle.com', 'Engineering (R&D)', 'Head Office', 'Engineer'),
    ('K0920', 'ROHIT KUMAR SHARMA', 'rohit.sharma@mahle.com', 'Maintenance', 'Parwanoo-1', 'Sr. Engineer'),
    ('K0927', 'AMIT KUMAR', 'hrd.khd@mahle.com', 'Production', 'Khandsa', 'Engineer'),
    ('K0988', 'Gagandeep Singh', 'gagandeep.a.singh@mahle.com', 'Central Purchase', 'Head Office', 'Manager'),
    ('KA1092', 'Manju', NULL, 'Production', 'Khandsa', 'Engineer'),
    ('KA1112', 'Bhawana Singh', NULL, 'Production', 'Khandsa', 'GET'),
    ('KA1151', 'Sakshi Upadhyay', NULL, 'Production', 'Khandsa', 'GET'),
    ('KA1235', 'Gaurav', 'Gaurav.Pasrija@mahle.com', 'HR', 'Khandsa', 'Asst. Manager'),
    ('KH0083', 'Shalender Yadav', 'Shalender.yadav@mahle.com', 'Central Process', 'Head Office', 'GM'),
    ('KH0109', 'Dharam Vir Mehra', 'dharamvir.mehra@mahle.com', 'Engineering (R&D)', 'Head Office', 'DGM'),
    ('KH0130', 'Neeraj Kumar', 'neeraj.kumar@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Manager'),
    ('KH0142', 'Mahender  KUMAR', 'mahender.kumar@mahle.com', 'Finance', 'Head Office', 'Executive'),
    ('KH0155', 'Rakesh Kumar', 'rakesh.kumar@mahle.com', 'OPERATIONS', 'Khandsa', 'DGM'),
    ('KH0183', 'N Suresh Babu', 'suresh.babu@mahle.com', 'After Market', 'Head Office', 'AGM'),
    ('KH0194', 'S.Nagender', 's.nagender@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0215', 'Gautam Prakash', 'gautam.prakash@mahle.com', 'After Market', 'Head Office', 'Sr. Manager'),
    ('KH0232', 'Udhvir Singh Bhandari', 'uday.bhandari@mahle.com', 'HR', 'Khandsa', 'Manager'),
    ('KH0254', 'Ayush Gupta', 'ayush.gupta@mahle.com', 'Central Purchase', 'Head Office', 'AGM'),
    ('KH0265', 'Nirmal Dhiman', 'nirmal.dhiman@mahle.com', 'Supply Chain', 'Head Office', 'Sr. Manager'),
    ('KH0286', 'Turlen Jamira Topno', 'turlenjamira.topno@mahle.com', 'Dispatch', 'CHENNAI', 'Asst. Manager'),
    ('KH0287', 'Surendra  Prajapati', 'surendra.prajapati@mahle.com', 'Quality', 'Khandsa', 'Asst. Manager'),
    ('KH0289', 'Deepanshu  Kalia', 'deepanshu.kalia@mahle.com', 'Central Process', 'Head Office', 'AGM'),
    ('KH0308', 'Sajith V P', 'sajith.nair@mahle.com', 'After Market', 'Head Office', 'Manager'),
    ('KH0311', 'Rajesh Kumar', 'rajesh.kumar1@mahle.com', 'Engineering (R&D)', 'Head Office', 'Assistant Manager'),
    ('KH0330', 'Devajit Kumar Thakuriah', 'devajit.thakuriah@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0364', 'Shivam Mehta', 'shivam.a.mehta@mahle.com', 'SCM', 'Khandsa', 'Sr. Manager'),
    ('KH0370', 'Yogesh Kumar Mor', 'yogesh.mor@mahle.com', 'Engineering (R&D)', 'Head Office', 'Manager'),
    ('KH0389', 'Puneet Singla', 'puneet.singla@mahle.com', 'Engineering (R&D)', 'Head Office', 'GM'),
    ('KH0396', 'Sk Faizul Haque', 'faizul.haque@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0398', 'Pavan Gedam', 'pavan.gedam@mahle.com', 'Engineering (R&D)', 'Head Office', 'Manager'),
    ('KH0399', 'Rakesh Kumar', 'rakesh.c.kumar@mahle.com', 'Central Purchase', 'Head Office', 'Sr. Manager'),
    ('KH0415', 'Manish Sharma', 'manish.sharma@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Manager'),
    ('KH0420', 'Vinod Kumar Suthar', 'vinod.d.kumar@mahle.com', 'Finance', 'Head Office', 'Manager'),
    ('KH0438', 'Chander Shekhar', 'Chander.shekhar@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Engineer'),
    ('KH0449', 'Ajay Chaturvedi', 'ajay.chaturvedi@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0453', 'Paramhans Dhir', 'paramhans.a.dhir@mahle.com', 'HR', 'Head Office', 'Sr. Executive'),
    ('KH0454', 'Anil Arora', 'anil.a.arora@mahle.com', 'Finance', 'CHENNAI', 'Manager'),
    ('KH0457', 'Harish Kumar', 'harish.a.kumar@mahle.com', 'Central Quality', 'Head Office', 'Manager'),
    ('KH0458', 'Vishal Sain', 'vishal.sain@mahle.com', 'OE Marketing', 'Head Office', 'AGM'),
    ('KH0460', 'Lalit Kumar Verma', 'lalit.verma@mahle.com', 'General Management', 'Head Office', 'GM'),
    ('KH0470', 'Sheetal Khurana', 'sheetal.khurana@mahle.com', 'After Market', 'Head Office', 'Manager'),
    ('KH0475', 'Rajesh Saklani', 'rajesh.saklani@mahle.com', 'Finance', 'Head Office', 'Manager'),
    ('KH0481', 'Mukul Sharma', 'mukul.a.sharma@mahle.com', 'Engineering (R&D)', 'Head Office', 'Asst. Manager'),
    ('KH0483', 'Abhinav Gandotra', 'abhinav.gandotra@mahle.com', 'Finance & IT', 'Head Office', 'SGM'),
    ('KH0485', 'Parvesh .', 'parvesh.kumar@mahle.com', 'After Market', 'Head Office', 'Sr. Engineer'),
    ('KH0495', 'Javed Khan', 'javed.aa.khan@mahle.com', 'Central Purchase', 'Head Office', 'SGM'),
    ('KH0500', 'Shambhu Das Singh', 'shambhu.singh@mahle.com', 'Engineering (R&D)', 'Head Office', 'Manager'),
    ('KH0501', 'Madan Mohan Saini', 'madanmohan.a.saini@mahle.com', 'OE Marketing', 'Head Office', 'Manager'),
    ('KH0503', 'Parmod Kumar', 'parmod.kumar@mahle.com', 'Central Quality', 'Head Office', 'Sr. Engineer'),
    ('KH0504', 'Ankush Bhan', 'ankush.a.bhan@mahle.com', 'OE Marketing', 'Head Office', 'AGM'),
    ('KH0510', 'Manish Sharma', 'manish.a.sharma@mahle.com', 'Process Engineering', 'Khandsa', 'Asst. Manager'),
    ('KH0512', 'Manikannan', 'c.manikannan@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0516', 'Devender Kumar Sharma', 'devender.sharma@mahle.com', 'Engineering (R&D)', 'Head Office', 'Asst. Manager'),
    ('KH0522', 'Shyam Nandan Kumar', 'shyam.a.nandan@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Manager'),
    ('KH0527', 'Narender Khatri', 'narender.khatri@mahle.com', 'Engineering (R&D)', 'Head Office', 'Asst. Manager'),
    ('KH0529', 'Senthilkumar Boominathan', 'Senthilkumar.Boominathan@mahle.com', 'Central Quality', 'Chennai-HO', 'Sr. Engineer'),
    ('KH0531', 'Viral Rajulal Mali', 'viral.mali@mahle.com', 'Central Process', 'Head Office', 'Manager'),
    ('KH0532', 'Ramanujan G', 'ramanujan.g@mahle.com', 'Process Engineering', 'CHENNAI', 'Asst. Manager'),
    ('KH0535', 'Vaibhav Narendra Goel', 'vaibhav.a.goel@mahle.com', 'After Market', 'Head Office', 'Manager'),
    ('KH0537', 'Akshay Prabhune', 'akshay.prabhune@mahle.com', 'Finance', 'Head Office', 'Asst. Manager'),
    ('KH0538', 'P Arun Kumar', 'arunkumar.paramasivam@mahle.com', 'Tooling', 'Head Office', 'Asst. Manager'),
    ('KH0540', 'Tirath Singh', 'tirath.singh@mahle.com', 'Engineering (R&D)', 'Head Office', 'AGM'),
    ('KH0542', 'Jagdish Joshi', 'jagdish.joshi@mahle.com', 'Finance', 'Head Office', 'Asst. Manager'),
    ('KH0544', 'Sanjay Yadav', 'sanjay.b.yadav@mahle.com', 'After Market', 'Head Office', 'GM'),
    ('KH0545', 'Vikas Kumar', 'vikas.a.kumar@mahle.com', 'Central Purchase', 'Head Office', 'Manager'),
    ('KH0548', 'Yogesh Yadav', 'yogesh.b.yadav@mahle.com', 'Finance', 'Head Office', 'Assistant Manager'),
    ('KH0551', 'Prateek Pandey', 'prateek.pandey@mahle.com', 'Central Purchase', 'Head Office', 'Asst. Manager'),
    ('KH0552', 'Anshul Jain', 'Anshul.a.Jain@mahle.com', 'Finance', 'Head Office', 'Asst. Manager'),
    ('KH0553', 'Samridhee', 'samridhee.jain@mahle.com', 'Finance', 'Head Office', 'Asst. Manager'),
    ('KH0554', 'Ashish Kumar', 'ashish.d.kumar@mahle.com', 'Engineering (R&D)', 'Head Office', 'Manager'),
    ('KH0555', 'PANKAJ KUMAR SAVITA', 'pankajkumar.savita@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0556', 'Madan Lal Jat', 'madan.lal@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0561', 'Rohit Khurana', 'rohit.khurana@mahle.com', 'Central Process', 'Head Office', 'Manager'),
    ('KH0562', 'Love Kumar', 'love.kumar@mahle.com', 'Finance', 'Head Office', 'Sr. Manager'),
    ('KH0563', 'Damian Patrick Christhuraj', 'Damian.Patrick@mahle.com', 'Central Quality', 'Chennai-HO', 'Asst. Manager'),
    ('KH0564', 'Neha Chaurasia', 'neha.chaurasia@mahle.com', 'After Market', 'Head Office', 'Manager'),
    ('KH0565', 'Suraj Singh', 'suraj.a.singh@mahle.com', 'Finance', 'Head Office', 'Manager'),
    ('KH0566', 'Saurabh Pratap Singh', 'saurabh.singh@mahle.com', 'Quality', 'Khandsa', 'Sr. Manager'),
    ('KH0567', 'Anita Kumari', 'anita.kumari@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0570', 'Shivani Tiwari', 'shivani.tiwari@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Engineer'),
    ('KH0572', 'Aniket Gupta', 'aniket.gupta@mahle.com', 'Engineering (R&D)', 'Head Office', 'Manager'),
    ('KH0574', 'Amrit Bhambi', 'amrit.bhambi@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0575', 'Deepak Rawat', 'deepak.b.rawat@mahle.com', 'Engineering (R&D)', 'Head Office', 'Manager'),
    ('KH0576', 'Sushant Sen', 'sushant.sen@mahle.com', 'After Market', 'Head Office', 'Manager'),
    ('KH0578', 'Ankur Malik', 'ankur.malik@mahle.com', 'Central Purchase', 'Head Office', 'Asst. Manager'),
    ('KH0579', 'Rajendra Kumar', 'rajendra.c.kumar@mahle.com', 'Supply Chain', 'Head Office', 'Sr. Executive'),
    ('KH0581', 'Twinkle Shukla', 'twinkle.shukla@mahle.com', 'HR', 'Head Office', 'Sr. Executive'),
    ('KH0582', 'Vijay Karde', 'vijay.karde@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0585', 'Kunal Bidla', 'kunal.bidla@mahle.com', 'HR', 'Head Office', 'Assistant Manager'),
    ('KH0587', 'Rakesh Vasudev Patil', 'rakesh.patil@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0588', 'Manish  Kumar', 'manish.c.kumar@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Manager'),
    ('KH0589', 'Manish Kumar Gupta', 'manish.a.gupta@mahle.com', 'PROJECT MANAGEMENT', 'Head Office', 'Manager'),
    ('KH0590', 'Debi Prasad Tripathy', 'debiprasad.tripathy@mahle.com', 'Central Purchase', 'Head Office', 'Manager'),
    ('KH0593', 'Utsav Kumar Singh', 'utsavkumar.singh@mahle.com', 'Central Process', 'Head Office', 'Sr. Engineer'),
    ('KH0595', 'Kashish Koundal', 'kashish.koundal@mahle.com', 'Finance', 'Head Office', 'Asst. Manager'),
    ('KH0596', 'Diksha Taori', 'diksha.taori@mahle.com', 'Finance', 'Head Office', 'Sr. Manager'),
    ('KH0597', 'Anupam Dikshit', 'anupam.dikshit@mahle.com', 'Central Purchase', 'Head Office', 'Sr. Manager'),
    ('KH0598', 'Rajendra Kumar Jain', 'rk.jain@mahle.com', 'General Management & Operations', 'Head Office', 'President - COO'),
    ('KH0599', 'Chaytali Dass', 'chaytali.a.dass@mahle.com', 'General Management', 'Head Office', 'Sr. Executive'),
    ('KH0600', 'Chhavi Sharma', 'chhavi.sharma@mahle.com', 'Central Quality', 'Head Office', 'Senior Manager'),
    ('KH0602', 'Saravanan', 'saravanan.arumugam@mahle.com', 'Tooling', 'Chennai-HO', 'Sr. Engineer'),
    ('KH0603', 'SATYA PRAKASH SINGH', 'satyaprakash.singh@mahle.com', 'EHS', 'Head Office', 'Sr. Manager'),
    ('KH0606', 'Neeraj Asgotra', 'neeraj.asgotra@mahle.com', 'Engineering (R&D)', 'Head Office', 'Senior Engineer'),
    ('KH0607', 'Sanjay Rahangdale', 'sanjay.rahangdale@mahle.com', 'After Market', 'Head Office', 'Assistant Manager'),
    ('KH0608', 'Abhinav Balwan', 'abhinav.balwan@mahle.com', 'HR', 'Head Office', 'AGM'),
    ('KH0609', 'Tapash Bera', 'tapash.bera@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0610', 'M Maheshwaran', 'maheshwaran.m@mahle.com', 'OE Marketing', 'Chennai-HO', 'Manager'),
    ('KH0612', 'Kamlesh Kumar', 'kamlesh.a.kumar@mahle.com', 'Central Quality', 'Chennai-HO', 'Engineer'),
    ('KH0614', 'Sandeep .', 'sandeep.thaledi@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0615', 'Laitonjam Manisankar Singha', 'manisankar.singha@mahle.com', 'After Market', 'Head Office', 'Sr. Manager'),
    ('KH0616', 'Deeksha Rahi', 'diksha.rahi@mahle.com', 'OE Marketing', 'Head Office', 'Asst. Manager'),
    ('KH0617', 'Vikas Aggarwal', 'vikas.aggarwal@mahle.com', 'R&D', 'Head Office', 'Sr. VP'),
    ('KH0618', 'Arjun Singh', 'arjun.singh@mahle.com', 'Engineering (R&D)', 'Head Office', 'Sr. Engineer'),
    ('KH0619', 'Himanshu Vasudeva', 'himanshu.vasudeva@mahle.com', 'Central Process', 'Head Office', 'Manager'),
    ('KH0620', 'Akib Yunussalim Mansuri', 'akib.mansuri@mahle.com', 'Engineering (R&D)', 'Head Office', 'Asst. Manager'),
    ('KH0621', 'Mukundam Shirisha', 'mukundam.shirisha@mahle.com', 'Central Process', 'Head Office', 'Senior Engineer'),
    ('KH0623', 'Manthan .', 'manthan.bakshi@mahle.com', 'Supply Chain', 'Head Office', 'Senior Engineer'),
    ('KH0624', 'Drishti Miglani', 'drishti.miglani@mahle.com', 'Finance', 'Head Office', 'Asst. Manager'),
    ('KH0625', 'Manish kumar Sahal', 'manish.sahal@mahle.com', 'Central Purchase', 'Head Office', 'Assistant Manager'),
    ('KH0627', 'Mukesh Kumar', 'mukesh.b.kumar@mahle.com', 'After Market', 'Head Office', 'Assistant Manager'),
    ('KH0628', 'Naman Agarwal', 'naman.a.agarwal@mahle.com', 'Finance', 'Head Office', 'Senior Executive'),
    ('KH0630', 'Nitin Chaudhari', 'nitin.chaudhari@mahle.com', 'After Market', 'Head Office', 'Senior Manager'),
    ('KH0631', 'Munagala Venkata Leela Sai', 'venkata.leela@mahle.com', 'After Market', 'Head Office', 'Asst. Manager'),
    ('KH0632', 'Anand Mohan Singh', 'anand.singh@mahle.com', 'After Market', 'Head Office', 'Assistant Manager'),
    ('KH0633', 'Pragya Singh', 'pragya.singh@mahle.com', 'HR', 'Head Office', 'Senior Manager'),
    ('KH0634', 'Manisha Kumari', 'manisha.a.kumari@mahle.com', 'Engineering (R&D)', 'Head Office', 'Assistant Manager'),
    ('KH0635', 'Ruchit Bhardwaj', 'ruchit.bhardwaj@mahle.com', 'Finance', 'Head Office', 'Assistant Manager'),
    ('KH0637', 'Rekha Sandhu', 'rekha.sandhu@mahle.com', 'HR', 'Head Office', 'SGM'),
    ('KH0638', 'Lakshita', 'lakshita.solanki@mahle.com', 'Finance', 'Head Office', 'Senior Executive'),
    ('KH0639', 'Peter K V', 'peter.kv@mahle.com', 'Central Process', 'Chennai-HO', 'Assistant Manager'),
    ('KH0640', 'Prashant Sahebrao Pawar', 'prashant.pawar@mahle.com', 'OPERATIONS', 'Head Office', 'Senior Vice President'),
    ('KH0641', 'Arpit Gupta', 'arpit.a.gupta@mahle.com', 'Sales & Applications', 'Head Office', 'Sr. GM'),
    ('KH0642', 'Hit Lal', 'hit.lal@mahle.com', 'Finance', 'Head Office', 'Manager'),
    ('KH0643', 'M SATRUGHANA PATRA', 'satrughana.patra@mahle.com', 'Central Quality', 'Head Office', 'AM'),
    ('KH0644', 'DUSHYANT AGARWAL', 'dushyant.agarwal@mahle.com', 'Finance', 'Head Office', 'Manager'),
    ('KH0645', 'Thiyagranjan Ganesan', 'thiyagarajan.g@mahle.com', 'Central Process', 'Head Office', 'Senior Manager'),
    ('KH0646', 'Anil Kumar Singh', 'anilkumar.singh@mahle.com', 'SCM', 'Head Office', 'Manager'),
    ('KH0647', 'Sandeepan Kar', 'sandeepan.kar@mahle.com', 'HR', 'Head Office', 'Senior Manager'),
    ('KH0648', 'Vijay Tanwani', 'vijay.tanwani@mahle.com', 'Finance', 'Head Office', 'Senior Manager'),
    ('KH0649', 'YATISH RAJ Y', 'yatish.raj@mahle.com', 'After Market', 'Head Office', 'Assistant Manager'),
    ('KH0650', 'Rahul Singh Rana', 'rahulsingh.rana@mahle.com', 'Central Quality', 'Head Office', 'Manager'),
    ('KH0651', 'AASHISH RAI', 'aashish.rai@mahle.com', 'Quality', 'Head Office', 'GET'),
    ('KH0652', 'Anway Walke', 'anway.walke@mahle.com', 'Engineering (R&D)', 'Head Office', 'Management Trainee'),
    ('KH0653', 'HARSHA VARDHAN S', 'harsha.vardhan@mahle.com', 'SCM', 'Head Office', 'GET'),
    ('KH0654', 'Yuvan Chophla', NULL, 'Central Process', 'Head Office', 'GET'),
    ('KH0655', 'Chebolu Pranay', NULL, 'Process Engineering', 'Head Office', 'GET');
GO

-- 3. Insert into dbo.EmpRoles
INSERT INTO dbo.EmpRoles (Emp_No, Role, IsHOD, IsPanelJudge, IsAdmin, Gender, UpdatedAt)
VALUES
    ('1332', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1335', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1336', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1337', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1351', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1656', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1693', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1729', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1754', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1806', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1825', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1828', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1914', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1935', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('2028', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('2162', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('2234', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6505', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6579', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6637', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6642', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6670', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6671', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('6673', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6676', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6681', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6682', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6685', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6687', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6688', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6689', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6690', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6691', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6692', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6694', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6696', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6699', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6701', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6703', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6706', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6707', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6708', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6709', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6711', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6712', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6713', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1002', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1009', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1027', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1030', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1031', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1033', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1048', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1052', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1077', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1078', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1084', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1088', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1089', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1092', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1098', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1099', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1105', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1107', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1108', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1109', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1110', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1112', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1113', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1114', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1116', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1117', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1118', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1119', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1120', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1121', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1122', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('1123', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6007', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6009', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6074', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6096', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6126', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6139', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6165', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6187', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('6215', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('8021', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('8409', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('8411', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('8412', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('8413', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E20067', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E20070', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E20089', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E20196', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40002', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40007', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40022', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40032', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40041', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40053', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40055', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40065', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40069', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40073', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40074', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40075', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40082', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40090', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40093', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40100', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40101', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40103', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40209', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40292', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40297', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E40370', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50002', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50003', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50013', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50037', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50039', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50045', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50076', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50108', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50135', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50162', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50203', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50278', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50322', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50332', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50396', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50432', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50433', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('E50438', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0060', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0075', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0099', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01003', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01013', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01028', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01030', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01069', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01104', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01140', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01144', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('K01146', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01149', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01151', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01152', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01153', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01154', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01162', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01163', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01164', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01166', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01167', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01168', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01169', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01170', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01171', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K01172', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0350', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0378', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0407', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0433', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0462', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0569', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0577', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0592', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0610', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0676', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0692', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0693', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0713', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0723', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0729', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0742', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0750', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0771', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0773', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0777', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0800', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0822', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0826', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0827', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0845', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0854', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0856', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0867', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0871', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0915', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0920', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0927', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('K0988', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KA1092', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KA1112', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KA1151', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KA1235', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0083', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0109', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0130', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0142', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0155', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0183', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0194', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0215', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0232', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0254', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0265', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0286', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0287', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0289', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0308', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0311', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0330', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0364', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0370', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0389', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0396', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0398', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0399', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0415', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0420', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0438', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0449', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0453', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0454', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0457', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0458', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0460', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0470', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0475', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0481', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0483', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0485', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0495', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0500', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0501', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0503', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0504', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0510', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0512', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0516', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0522', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0527', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0529', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0531', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0532', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0535', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0537', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0538', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0540', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0542', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0544', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0545', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0548', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0551', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0552', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0553', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0554', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0555', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0556', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0561', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0562', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0563', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0564', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0565', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0566', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0567', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0570', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0572', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0574', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0575', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0576', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0578', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0579', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0581', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0582', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0585', 'admin', 0, 0, 1, NULL, GETDATE()),
    ('KH0587', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0588', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0589', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0590', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0593', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0595', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0596', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0597', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0598', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0599', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0600', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0602', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0603', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0606', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0607', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0608', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0609', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0610', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0612', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0614', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0615', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0616', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0617', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0618', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0619', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0620', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0621', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0623', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0624', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0625', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0627', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0628', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0630', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0631', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0632', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0633', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0634', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0635', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0637', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0638', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0639', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0640', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0641', 'hod', 1, 0, 0, NULL, GETDATE()),
    ('KH0642', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0643', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0644', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0645', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0646', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0647', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0648', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0649', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0650', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0651', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0652', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0653', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0654', 'employee', 0, 0, 0, NULL, GETDATE()),
    ('KH0655', 'employee', 0, 0, 0, NULL, GETDATE());
GO

PRINT '=== Successfully seeded all employees, HODs, and Admin into dbo.Employees & dbo.EmpRoles ===';
GO


USE [Rewards];
GO
ALTER TABLE dbo.EmpRoles DROP CONSTRAINT FK_EmpRoles_Employees;
ALTER TABLE dbo.EmpPasswords DROP CONSTRAINT FK_EmpPasswords_Employees;

ALTER TABLE dbo.EmpRoles 
    ADD CONSTRAINT FK_EmpRoles_Employees 
    FOREIGN KEY (Emp_No) REFERENCES dbo.Employees(Emp_No)
    ON DELETE CASCADE 
    ON UPDATE CASCADE; 

ALTER TABLE dbo.EmpPasswords 
    ADD CONSTRAINT FK_EmpPasswords_Employees 
    FOREIGN KEY (Emp_No) REFERENCES dbo.Employees(Emp_No)
    ON DELETE CASCADE 
    ON UPDATE CASCADE; 
GO

USE [Rewards];
GO

-- 1. Drop Foreign Key constraints
ALTER TABLE dbo.EmpRoles DROP CONSTRAINT IF EXISTS FK_EmpRoles_Employees;
ALTER TABLE dbo.EmpPasswords DROP CONSTRAINT IF EXISTS FK_EmpPasswords_Employees;

-- 2. Truncate Tables
TRUNCATE TABLE dbo.EmpPasswords;
TRUNCATE TABLE dbo.EmpRoles;
TRUNCATE TABLE dbo.Employees;

-- 3. Re-add Foreign Keys with CASCADE
ALTER TABLE dbo.EmpRoles ADD CONSTRAINT FK_EmpRoles_Employees
    FOREIGN KEY (Emp_No) REFERENCES dbo.Employees(Emp_No)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE dbo.EmpPasswords ADD CONSTRAINT FK_EmpPasswords_Employees
    FOREIGN KEY (Emp_No) REFERENCES dbo.Employees(Emp_No)
    ON DELETE CASCADE ON UPDATE CASCADE;
GO
